// C4D-DialogResource
DIALOG IDD_DIALOG_MAIN
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC4; SCALE_V; SCALE_H; 
    BORDERSTYLE BORDER_NONE; BORDERSIZE 10, 0, 10, 0; 
    COLUMNS 1;
    
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC1; SCALE_V; SCALE_H; 
      BORDERSTYLE BORDER_GROUP_TOP; BORDERSIZE 20, 7, 20, 5; 
      COLUMNS 2;
      SPACE 4, 4;
      
      STATICTEXT IDC_STATIC_SPLIT_REGEX { NAME IDS_STATIC; CENTER_V; CENTER_H; }
      MULTILINEEDIT IDC_EDIT_SPLIT_REGEX
      { 
        ALIGN_TOP; SCALE_H; SIZE 374, 22; 
        MONOSPACED; SYNTAXCOLOR; PYTHON; 
      }
      STATICTEXT IDC_STATIC_FIXES { NAME IDS_STATIC3; CENTER_V; CENTER_H; }
      MULTILINEEDIT IDC_EDIT_NAMEFIXES
      { 
        SCALE_V; FIT_H; SIZE 390, 80; 
        MONOSPACED; SYNTAXCOLOR; PYTHON; 
      }
    }
    SEPARATOR { SCALE_H; }
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC2; ALIGN_TOP; CENTER_H; 
      BORDERSIZE 0, 0, 0, 5; 
      COLUMNS 2;
      SPACE 4, 4;
      
      BUTTON IDC_BUTTON_CANCEL { NAME IDS_BUTTON1; ALIGN_TOP; ALIGN_LEFT; }
      BUTTON IDC_BUTTON_START { NAME IDS_BUTTON; ALIGN_TOP; ALIGN_LEFT; }
    }
  }
}